version: "3"
services:
  app:
    build: 
      context: &naia_context ..
      dockerfile: &naia_dockerfile ci/Dockerfile
      args:
        APP_COPY: naia
    env_file: &naia_env .env
    image: naia-app
    ports: &naia_ports
      - 5309:5309

  local:
    build: 
      context: *naia_context
      dockerfile: *naia_dockerfile
      args:
        POETRY_ARGS: --with static_tools,docs
    env_file: *naia_env
    environment:
      RELOAD: true
    image: naia-local
    volumes:
      - ${PWD}/naia/:/naia/naia
      - ${PWD}/pyproject.toml:/naia/pyproject.toml
    ports: *naia_ports

  test:
    build: 
      context: *naia_context
      dockerfile: *naia_dockerfile
      args:
        POETRY_ARGS: --with static_tools,test
    env_file: *naia_env
    environment:
      RELOAD: false
    image: naia-test
    volumes:
      - ${PWD}/naia/:/naia/naia
      - ${PWD}/tests:/naia/tests
      - ${PWD}/pyproject.toml:/naia/pyproject.toml
    ports: *naia_ports

  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"